# Change these first
owner: InetIntel # Your GitHub organization or username, where this repository lives
repo: service-monitoring # The name of this repository

sites:
  - name: IODA website
    url: https://ioda.inetintel.cc.gatech.edu
  - name: GRIP website
    url: https://grip.inetintel.cc.gatech.edu
  - name: IODA API
    url: https://api.ioda.inetintel.cc.gatech.edu/v2/
  - name: GRIP API
    url: https://api.grip.inetintel.org/json/events?length=10&start=0&ts_start=2023-05-01T00%3A00&ts_end=2023-05-02T00%3A00&event_type=submoas&full
  - name: GRIP API blocklist
    url: https://api.grip.inetintel.cc.gatech.edu/json/blocklist
  - name: InetIntel lab website
    url: https://inetintel.cc.gatech.edu/
  - name: IODA grafana
    url: https://explore.ioda.inetintel.cc.gatech.edu
  - name: GRIP grafana
    url: https://explore.grip.inetintel.cc.gatech.edu

assignees:
 - salcock

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /service-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Internet Intelligence Lab Service Monitoring
  introTitle: "Is the (IODA / GRIP) website down or is it just me?"
  introMessage: Live status updates for websites and other services operated by the Internet Intelligence Lab at Georgia Tech. More info about the lab can be found at https://inetintel.cc.gatech.edu/. This service is powered by Upptime, an open-source uptime monitor and status page, that operates entirely on GitHub.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
